# Generated by Django 5.2.6 on 2025-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(blank=True, max_length=40)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('recording_url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('referrer', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('website', 'Website Click'), ('call', 'Call Click')], max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
